esphome:
  name: "pc-control"
  platformio_options:
   board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

switch:
  - platform: gpio
    pin: 3
    name: "PC power on/off"
    inverted: true
    id: relay
    on_turn_on:
    - delay: 500ms
    - switch.turn_off: relay

esp32_ble_tracker:
  on_ble_manufacturer_data_advertise:
    - mac_address: C7:35:33:33:66:73
      manufacturer_id: '0001'
      then:
        - lambda: |-
            const int basenum = (int16_t(x[2]) << 16) + (int16_t(x[3]) << 8) + int16_t(x[4]);
            const float temperature = (basenum / 10000.0f);
            const float humidity = (basenum % 1000) / 10.0f;
            const float battery_level = uint16_t(x[5]) / 1.0f;

            id(hallway_temperature).publish_state(temperature);
            id(hallway_humidity).publish_state(humidity);
            id(hallway_battery).publish_state(battery_level);

binary_sensor:
  - platform: ble_presence
    mac_address: C7:35:33:33:66:73
    name: "Hallway Govee H5105"

sensor:
  - platform: ble_rssi
    mac_address: C7:35:33:33:66:73
    name: "Hallway RSSI"
  - platform: template
    name: "Hallway Humidity"
    id: hallway_humidity
    unit_of_measurement: '%'
    icon: "mdi:water-percent"
  - platform: template
    name: "Hallway Temperature"
    id: hallway_temperature
    unit_of_measurement: '°C'
    icon: "mdi:thermometer"
  - platform: template
    name: "Hallway Battery"
    id: hallway_battery
    unit_of_measurement: '%'
    icon: "mdi:battery"