esphome:
  name: office
  includes:
    - EsphomeClimateHoneywellAdapter.h
    - HoneywellManager_OpenHR20.h
    - HoneywellManager_HR20_V1.h
    - IHoneywellManager.h

esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:

ota:

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

uart:
  - id: uart_bus1
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE  
    tx_pin: GPIO1
    rx_pin: GPIO3
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n,\r,0"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new EsphomeClimateHoneywellAdapter(id(uart_bus1));
    App.register_component(my_custom_climate);
    return {my_custom_climate};

  climates:
    - name: "Office"


    