esphome:
  name: "livingroom"
  includes:
    - EsphomeClimateHoneywellAdapter.h
    - HoneywellManager_OpenHR20.h
    - HoneywellManager_HR20_V1.h
    - IHoneywellManager.h

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


captive_portal:

uart:
  - id: uart_bus1
    baud_rate: 2400
    data_bits: 8
    stop_bits: 1
    parity: EVEN  
    tx_pin: GPIO17
    rx_pin: GPIO16
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n,\r,0"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

sensor:
  - platform: dht
    pin: GPIO14
    temperature:
      id: living_room_temp
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 5min

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new EsphomeClimateHoneywellAdapter(id(uart_bus1), id(living_room_temp));
    App.register_component(my_custom_climate);
    return {my_custom_climate};

  climates:
    - name: "Livingroom"


    